<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppReport.mrt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AppReport.mrt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.CodeAnalysis" Version="4.13.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Stimulsoft.Base">
      <HintPath>report-dll\Stimulsoft.Base.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Controls">
      <HintPath>report-dll\Stimulsoft.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Controls.Win">
      <HintPath>report-dll\Stimulsoft.Controls.Win.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Data">
      <HintPath>report-dll\Stimulsoft.Data.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report">
      <HintPath>report-dll\Stimulsoft.Report.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report.Win">
      <HintPath>report-dll\Stimulsoft.Report.Win.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="databse.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>